/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "scrpvxcsmbgnhfqwqfuy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjcnB2eGNzbWJnbmhmcXdxZnV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczNTI1NzksImV4cCI6MjA4MjkyODU3OX0.iOrXMNpFDoeW9eYSk5gbDt5Vdu-RrGdSwU-0A5VNGho"