/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ukezmjxodwxzgikzwxlm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrZXptanhvZHd4emdpa3p3eGxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY4MzM2NzgsImV4cCI6MjA4MjQwOTY3OH0.wwqay9TeCgImOItDMdIYmNzNq0XhJT-e-QBBiBoAyVE"